package com.lelocabdriver.webservice;

/**
 * Created by ashish on 27-10-2016.
 */

public enum WebApiConstants {
    SIGN_UP,
    PASSWORD,
    GET_USER_RIDE_INFO,
    ACCEPT_RIDE, START_RIDE, LOGIN, CANCEL_RIDE, LOGOUT, GET_ALL_COMPLETE_RIDE_HISTORY, GET_COMPLETE_RIDE_DETAIL, GET_DRIVER_STATISTICS, GET_WALLET_DETAIL, UPDATE_DRIVER_LOCATION, GET_RUNNING_RIDE, COMPLETE_RIDE

}
